// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575099216);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575099336);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575098856);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1575099096);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575098976);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1574952510);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575099456);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1574949990);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{847c07b2-ecf2-48e7-94fa-eddbf66aa245}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575061200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 1);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1574966933);
user_pref("browser.onboarding.notification.prompt-count", 4);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575098831101");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575102431101");
user_pref("browser.search.countryCode", "MG");
user_pref("browser.search.region", "MG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181211232904");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575098828");
user_pref("browser.slowStartup.averageTime", 5720);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20181211232904");
user_pref("browser.startup.homepage_override.mstone", "60.4.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1574950030552");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "60.4.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Fri, 29 Nov 2019 22:22:46 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 25);
user_pref("extensions.getAddons.cache.lastUpdate", 1575099217);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181211232904");
user_pref("extensions.lastAppVersion", "60.4.0");
user_pref("extensions.lastPlatformVersion", "60.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"448249c4-463e-484b-8ba1-4e59a58fc950\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1574952231);
user_pref("media.gmp-manager.buildID", "20181211232904");
user_pref("media.gmp-manager.lastCheck", 1575098849);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1574952231);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "465a8de1-8cdb-4230-9521-add5bfedaa01");
user_pref("services.blocklist.addons.checked", 1575099330);
user_pref("services.blocklist.clock_skew_seconds", 6);
user_pref("services.blocklist.gfx.checked", 1575099330);
user_pref("services.blocklist.last_etag", "\"1575072019154\"");
user_pref("services.blocklist.last_update_seconds", 1575099330);
user_pref("services.blocklist.onecrl.checked", 1575099330);
user_pref("services.blocklist.pinning.checked", 1575099330);
user_pref("services.blocklist.plugins.checked", 1575099330);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1574952231);
user_pref("toolkit.startup.last_success", 1575098822);
user_pref("toolkit.telemetry.cachedClientID", "19b24370-3bd7-435f-ac0a-616154d5c241");
user_pref("toolkit.telemetry.previousBuildID", "20181211232904");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
